=== mectest1/HelloEE/HelloWeb7/WebContent/WEB-INF/config/EE_PARA_v2.6.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT EE_PARA (EE_LIB, EE_SYS, EEConfig, EELog, INTFConfig?, mfvr?, RMILog?, SignGraphics?, TRXATA?, VTB?)>

<!ELEMENT EE_LIB (entry*)>
<!ELEMENT EE_SYS (SYST?)>
<!ELEMENT EEConfig (entry*)>
<!ELEMENT EELog (entry*)>
<!ELEMENT INTFConfig (#PCDATA)>
<!ELEMENT mfvr (#PCDATA)>
<!ELEMENT RMILog (#PCDATA)>
<!ELEMENT SignGraphics (#PCDATA)>
<!ELEMENT TRXATA (#PCDATA)>
<!ELEMENT VTB (#PCDATA)>

<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry 
	type CDATA #IMPLIED
	name CDATA #IMPLIED
	desc CDATA #IMPLIED
>

<!ELEMENT SYST (entry*)>

=== mectest1/HelloEE/HelloWeb7/WebContent/WEB-INF/config/ee-para-dir-structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EE_PARA SYSTEM "EE_PARA_v2.6.dtd">
<!-- This fils is used to describe the file structure in EE_PARAM -->
<EE_PARA>
	<EE_LIB>
		<entry></entry>
	</EE_LIB>
	<EE_SYS>
		<SYST>
			<entry name="sys_para">sys_para.xml</entry>
		</SYST>
	</EE_SYS>
	<EEConfig>
		<entry></entry>
	</EEConfig>
	<EELog>
		<entry></entry>
	</EELog>
</EE_PARA>
